name: Build and Push Image API_VITIBRASIL
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: "production"
    env:
      IMAGE_NAME: "api-vitibrasil"
      REPOSITORY_NAME: "api-vitibrasil"
      GCP_PROJECT_ID: "thinking-leaf-440018-f4"
      REGION: "us-central1"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_DEPLOY }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Docker login to Google Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: us-central1-docker.pkg.dev
          username: "_json_key"
          password: ${{ secrets.GCP_SERVICE_ACCOUNT_DEPLOY }}

      - name: Configure Docker Client
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:latest .

      - name: Tag Docker image
        run: |
          docker tag $IMAGE_NAME:latest us-central1-docker.pkg.dev/$GCP_PROJECT_ID/$REPOSITORY_NAME/$IMAGE_NAME:latest

      - name: Push Docker image to Google Artifact Registry
        run: |
          docker push us-central1-docker.pkg.dev/$GCP_PROJECT_ID/$REPOSITORY_NAME/$IMAGE_NAME:latest
